### ISSUE TITLE
Unable to build for iOS (XCode 10.2.1)

### ISSUE THREAD

**Issue by mg** [konstantintuev/respect_24_hour#1]
Output:
![image](https://user-images.githubusercontent.com/1972/59803385-d7a5bd80-92da-11e9-8ace-38f5f9a45317.png)
Something about SWIFT_VERSION not being set, is this a new issue?

cheers

**Comment by mg** [comment]
>flutter doctor -v

[✓] Flutter (Channel dev, v1.7.4, on Mac OS X 10.14.5 18F132, locale en-IS)
    • Flutter version 1.7.4 at /Users/mg/Applications/flutter
    • Framework revision dfecafa4ab (6 days ago), 2019-06-14 09:46:23 -0700
    • Engine revision 2589785b5c
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mg/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone Xʀ • D80E896D-C8BE-4156-85E8-53EEEBD9439D • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

**Comment by konstantintuev** [comment]
Seems like a new error.
I have made a new package - [https://pub.dev/packages/is_24_hour_format](https://pub.dev/packages/is_24_hour_format).
Please replace the old `respect_24_hour` with `is_24_hour_format` in your pubspec and imports.
If it still reports the same error, please reopen/create new issue.
