### ISSUE TITLE
detection not always working

### ISSUE THREAD

**Issue by romk1n** [konstantintuev/respect_24_hour#2]
On some unicode languages like `Russian` the detection doesn't work. You probably need to use `jj` instead of just `j` to detect it.

https://mokagio.github.io/tech-journal/2015/01/13/ios-locale-hours-formatting.html

**Comment by konstantintuev** [comment]
Fixed in a new package - [https://pub.dev/packages/is_24_hour_format](https://pub.dev/packages/is_24_hour_format).
Please replace the old `respect_24_hour` with `is_24_hour_format` in your pubspec and imports.
